version: '3'

services:
  postgres:
    image: postgres
    container_name: form_service_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'form'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
      PGDATA: /var/lib/postgresql/data/form/
    volumes:
      - pgdata:/var/lib/postgresql/data/form
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
